# Generated by Django 2.2.6 on 2019-10-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry834',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupnum', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('assigned', models.CharField(max_length=20)),
                ('renewal', models.CharField(max_length=20)),
                ('fileType', models.CharField(max_length=20)),
                ('testFileName', models.CharField(max_length=100)),
                ('testDate', models.DateField(verbose_name='Test Date')),
                ('approvedWho', models.CharField(max_length=20)),
                ('prodFileName', models.CharField(max_length=100)),
                ('prodDate', models.DateField(verbose_name='Production Date')),
                ('analyticsVerified', models.CharField(max_length=20)),
                ('approvedWhoTwo', models.CharField(max_length=20)),
            ],
        ),
    ]
