# Generated by Django 2.2.6 on 2019-10-06 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='assignedTo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='folderName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='queryName',
            field=models.CharField(max_length=100),
        ),
    ]
