# Generated by Django 2.2.6 on 2019-10-07 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_auto_20191006_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='queryName',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
