# Generated by Django 2.2.6 on 2019-10-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=100)),
                ('whereFound', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('goodLink', models.BooleanField(default=False)),
                ('needed', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
